local plugin = require("my-telescope-spartan-plugin")

describe("my-telescope-spartan-plugin", function()
    describe("setup", function()
        it("has default config", function()
            local config = plugin.get_config()
            assert.is_table(config)
            assert.is_table(config.features)
            assert.equals("Task", config.features[1])
        end)

        it("merges user config", function()
            plugin.setup({
                features = { "Task", "Time" },
                keymaps = { task_info = "<C-n>" },
            })
            local config = plugin.get_config()
            assert.equals("Task", config.features[1])
            assert.equals("Time", config.features[2])
            assert.equals("<C-n>", config.keymaps.task_info)
        end)
    end)

    describe("taskwarrior module", function()
        it("loads taskwarrior module", function()
            local taskwarrior = require("my-telescope-spartan-plugin.taskwarrior")
            assert.is_table(taskwarrior)
            assert.is_function(taskwarrior.taskwarrior_init)
        end)

        it("taskwarrior_init returns a function", function()
            local taskwarrior = require("my-telescope-spartan-plugin.taskwarrior")
            local picker_fn = taskwarrior.taskwarrior_init({ features = { "Task" } })
            assert.is_function(picker_fn)
        end)
    end)

    describe("actions module", function()
        it("loads actions module", function()
            local actions = require("my-telescope-spartan-plugin.actions")
            assert.is_table(actions)
        end)

        it("has expected action functions", function()
            local actions = require("my-telescope-spartan-plugin.actions")
            assert.is_function(actions.task_edit)
            assert.is_function(actions.task_start)
            assert.is_function(actions.task_stop)
            assert.is_function(actions.task_annotate)
            assert.is_function(actions.task_info)
        end)
    end)
end)
